### ISSUE TITLE
[Bug]: Can't handle comments

### ISSUE THREAD

**Issue by matthewdeanmartin** [ThatXliner/unmarkd#28]
### Prerequisites

- [X] I have searched the [issues](https://github.com/ThatXliner/unmarkd/issues) and believe that it has not already been reported
- [X] I have made sure this bug reproduces on the latest version
- [X] I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### Bug description

It should be able to handle HTML comments

### Reproduction steps

This
```python
import unmarkd
result_md = unmarkd.unmark("<!-- first a comment-->")
print(result_md)
```

blows up like this
```
E:\.virtualenv\markdown_build-ameLEfbe\Scripts\python.exe E:\github\markdown_build\conversoins.py 
Traceback (most recent call last):
  File "E:\github\markdown_build\conversoins.py", line 5, in <module>
    result_md = unmarkd.unmark("<!-- first a comment-->")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\markdown_build-ameLEfbe\Lib\site-packages\unmarkd\__init__.py", line 11, in unmark
    return unmarkers.BasicUnmarker().unmark(html)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\markdown_build-ameLEfbe\Lib\site-packages\unmarkd\unmarkers.py", line 223, in unmark
    return self.__parse(html).strip().replace("\u0000", "\uFFFD")
           ^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\markdown_build-ameLEfbe\Lib\site-packages\unmarkd\unmarkers.py", line 118, in __parse
    output += self.resolve_handler_func(name)(child)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\.virtualenv\markdown_build-ameLEfbe\Lib\site-packages\unmarkd\unmarkers.py", line 93, in resolve_handler_func
    return getattr(self, "tag_" + name)
                         ~~~~~~~^~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

### Other information

python 3.11
beautifulsoup4==4.12.2

### Reproduces how often

I can reproduce this bug 100% of the time

**Comment by ThatXliner** [comment]
Nice catch!

**Comment by ThatXliner** [comment]
When I was fixing this, I found out that I should really update the old codebase. I've dropped Python 3.6 support (which had reached its EOL a long time ago) and Python 3.7 support (which is reaching its end of life in 2 weeks as of this comment)[^1]. Since dropping Python versions is a breaking change, I've incremented the major semver number. I will release soon

[^1]: https://endoflife.date/python
