### ISSUE TITLE
[REQUEST]: Converting directly from BeautifulSoup objects

### ISSUE THREAD

**Issue by LeMoussel** [ThatXliner/unmarkd#30]
### Prerequisites

- [X] I have searched the [issues](https://github.com/ThatXliner/unmarkd/issues) and believe that it has not already been requested (and possibly rejected)
- [X] I have made sure that this feature isn't possible with this project's plugin system and/or configuration; core changes must be made to make this happen.
- [X] I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### Feature description

Like [markdownify](https://github.com/matthewwithanm/python-markdownify#converting-beautifulsoup-objects) it would be interesting to convert directly from BeautifulSoup objects

eg: 
```
from markdownify import MarkdownConverter

# Create shorthand method for conversion
def md(soup, **options):
    return MarkdownConverter(**options).convert_soup(soup)
```

**Comment by ThatXliner** [comment]
It's already supported but just wasn't documented

**Comment by LeMoussel** [comment]
How can I do it ?

**Comment by ThatXliner** [comment]
Pass your `BeautifulSoup` object directly into any public `unmark` method or function https://github.com/ThatXliner/unmarkd/blob/666a81de4e9b0af5d55cb498b0391aebd7430f66/unmarkd/__init__.py#L10
